language: android
jdk: oraclejdk8

env:
  global:
    - OWNER=${TRAVIS_REPO_SLUG%/*}
    - DEV=${OWNER/oliexdev/dev}
    - BRANCH=${TRAVIS_BRANCH/master/}

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - extra-android-m2repository

branches:
  except:
    - /^travis-.*-build$/

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-26"

before_script:
  - sed -i -r
    -e 's/applicationId "[^"]+/\0.'${DEV}'/'
    -e 's/(versionCode ).*/\1'$(date +%s)'/'
    -e 's/versionName "[^"]+/\0-'${DEV}'_'${TRAVIS_COMMIT:0:8}_$(date +%F)'/'
    android_app/app/build.gradle
  - sed -i -r
    -e 's/(<string name="app_name"[^>]*>[^<]+)/\1 ('${DEV}${BRANCH}')/'
    android_app/app/src/main/res/values/strings.xml
  # Create keystore by running:
  #   keytool -genkey -v -keystore debug.keystore -storepass android \
  #     -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 \
  #     -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
  #
  # Then base64 encode it with:
  #   base64 -w0 debug.keystore
  #
  # Then add this to Travis environment variables as DEBUG_KEYSTORE (make sure
  # not to enable displaying value in build logs)"
  - test -n "$DEBUG_KEYSTORE"
    && echo "$DEBUG_KEYSTORE" | base64 -d > $HOME/.android/debug.keystore
    || true

script: cd android_app && ./gradlew testDebug assembleAndroidTest assembleDebug

before_deploy:
  - ln -s app/build/outputs/apk/debug/app-debug.apk openScale-${DEV}${BRANCH}-build.apk
  - git tag -f travis-${DEV}${BRANCH}-build
  - git remote add gh
    https://${OWNER}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh travis-${DEV}${BRANCH}-build
  - git remote remove gh

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: openScale-${DEV}${BRANCH}-build.apk
  skip_cleanup: true
  name: openScale development build (${TRAVIS_BRANCH})
  body: Automatic openScale development build of $TRAVIS_BRANCH
    ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    branch: master
